"""API module - External API clients and routes."""

from src.api.app import app, create_app, run_server
from src.api.coingecko import CoinGeckoClient
from src.api.dependencies import clear_agent, get_agent
from src.api.ghostfolio import GhostfolioClient
from src.api.models import (
    AgentConfigRequest,
    AgentConfigResponse,
    ChatRequest,
    ChatResponse,
    CostComparisonEntry,
    CostComparisonResponse,
    CostProjectionsResponse,
    ErrorResponse,
    EvalCaseResponse,
    EvalResultResponse,
    EvalResultsResponse,
    EvalRunRequest,
    EvalSummaryResponse,
    FeedbackRequest,
    FeedbackResponse,
    HealthResponse,
    ModelPricingEntry,
    ModelPricingResponse,
    PortfolioSummaryResponse,
    SeedDemoUsageResponse,
    SessionHistoryResponse,
    SessionsListResponse,
    SessionSummary,
    StrategyConfigResponse,
    StrategyRecommendationResponse,
    ToolCreateRequest,
    ToolDetailResponse,
    ToolExecuteRequest,
    ToolExecuteResponse,
    ToolRegistrationRequest,
    ToolRegistrationResponse,
    ToolResponse,
    TraceDetailResponse,
    TraceResponse,
    UsageByModel,
    UsageStatsResponse,
    VerificationConfigResponse,
)
from src.api.yahoo_finance import YahooFinanceClient

__all__ = [
    # API Clients
    "GhostfolioClient",
    "YahooFinanceClient",
    "CoinGeckoClient",
    # App
    "app",
    "create_app",
    "run_server",
    # Dependencies
    "get_agent",
    "clear_agent",
    # Models
    "ChatRequest",
    "ChatResponse",
    "HealthResponse",
    "FeedbackRequest",
    "FeedbackResponse",
    "PortfolioSummaryResponse",
    "SessionSummary",
    "SessionsListResponse",
    "SessionHistoryResponse",
    "ErrorResponse",
    "AgentConfigRequest",
    "AgentConfigResponse",
    "StrategyConfigResponse",
    "StrategyRecommendationResponse",
    "ToolResponse",
    "ToolCreateRequest",
    "ToolRegistrationRequest",
    "ToolRegistrationResponse",
    "ToolDetailResponse",
    "ToolExecuteRequest",
    "ToolExecuteResponse",
    "VerificationConfigResponse",
    "TraceResponse",
    "TraceDetailResponse",
    "EvalCaseResponse",
    "EvalResultResponse",
    "EvalSummaryResponse",
    "EvalResultsResponse",
    "EvalRunRequest",
    "UsageByModel",
    "UsageStatsResponse",
    "CostProjectionsResponse",
    "ModelPricingEntry",
    "ModelPricingResponse",
    "CostComparisonEntry",
    "CostComparisonResponse",
    "SeedDemoUsageResponse",
]
