"""API module - External API clients and routes."""

from src.api.ghostfolio import GhostfolioClient
from src.api.yahoo_finance import YahooFinanceClient
from src.api.coingecko import CoinGeckoClient
from src.api.app import app, create_app, run_server
from src.api.dependencies import get_agent, clear_agent
from src.api.models import (
    ChatRequest,
    ChatResponse,
    HealthResponse,
    FeedbackRequest,
    FeedbackResponse,
    PortfolioSummaryResponse,
    SessionSummary,
    SessionsListResponse,
    SessionHistoryResponse,
    ErrorResponse,
    AgentConfigRequest,
    AgentConfigResponse,
    StrategyConfigResponse,
    StrategyRecommendationResponse,
    ToolResponse,
    ToolCreateRequest,
    ToolRegistrationRequest,
    ToolRegistrationResponse,
    ToolDetailResponse,
    ToolExecuteRequest,
    ToolExecuteResponse,
    VerificationConfigResponse,
    TraceResponse,
    TraceDetailResponse,
    EvalCaseResponse,
    EvalResultResponse,
    EvalSummaryResponse,
    EvalResultsResponse,
    EvalRunRequest,
    UsageByModel,
    UsageStatsResponse,
    CostProjectionsResponse,
    ModelPricingEntry,
    ModelPricingResponse,
    CostComparisonEntry,
    CostComparisonResponse,
    SeedDemoUsageResponse,
)

__all__ = [
    # API Clients
    "GhostfolioClient",
    "YahooFinanceClient",
    "CoinGeckoClient",
    # App
    "app",
    "create_app",
    "run_server",
    # Dependencies
    "get_agent",
    "clear_agent",
    # Models
    "ChatRequest",
    "ChatResponse",
    "HealthResponse",
    "FeedbackRequest",
    "FeedbackResponse",
    "PortfolioSummaryResponse",
    "SessionSummary",
    "SessionsListResponse",
    "SessionHistoryResponse",
    "ErrorResponse",
    "AgentConfigRequest",
    "AgentConfigResponse",
    "StrategyConfigResponse",
    "StrategyRecommendationResponse",
    "ToolResponse",
    "ToolCreateRequest",
    "ToolRegistrationRequest",
    "ToolRegistrationResponse",
    "ToolDetailResponse",
    "ToolExecuteRequest",
    "ToolExecuteResponse",
    "VerificationConfigResponse",
    "TraceResponse",
    "TraceDetailResponse",
    "EvalCaseResponse",
    "EvalResultResponse",
    "EvalSummaryResponse",
    "EvalResultsResponse",
    "EvalRunRequest",
    "UsageByModel",
    "UsageStatsResponse",
    "CostProjectionsResponse",
    "ModelPricingEntry",
    "ModelPricingResponse",
    "CostComparisonEntry",
    "CostComparisonResponse",
    "SeedDemoUsageResponse",
]
